Initial Elevator
team4099/ChargedUp-2023 pull request #15
Opened 2023-01-09 23:48 UTC by CodingMaster121

Draft Elevator Pull Request

2023-01-21 03:22 UTC, sswadkar requested changes
looks swag. good stuff fr ‼️ i made some general improvement recommendations, take a look at them and feel free to ask any questions :)

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/commands/elevator/ElevatorCharacterizeCommand.kt
> +class ElevatorCharacterizeCommand(val elevator: Elevator) : CommandBase() {
this isn't really characterization this is just getting your kS + kG value: the amount of voltage needed to overcome static friction and gravity

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/commands/elevator/ElevatorIdleCommand.kt
> +class ElevatorIdleCommand(val elevator: Elevator) : CommandBase() {
should delete this since we command factory idle command

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/commands/elevator/OpenLoopExtendElevatorCommand.kt
> +class OpenLoopExtendElevatorCommand(val elevator: Elevator) : CommandBase() {
should delete since we command factory this

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/commands/elevator/OpenLoopRetractElevatorCommand.kt
> +class OpenLoopRetractElevatorCommand(val elevator: Elevator) : CommandBase() {
should delete since we command factory this

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/config/constants/ElevatorConstants.kt
> +  val ELEVATOR_ANGLE = 51.687235.degrees
sig figs pls 😭

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/config/constants/ElevatorConstants.kt
> +  val ELEVATOR_KS = 0.584.volts // TODO tune
we should separate the kS value for sim vs IRL

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/ElevatorIO.kt
> +    var leaderAppliedOutput = 0.0
log voltage instead of applied output

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/ElevatorIONeo.kt
> +  override fun configPID(
this won't work. for us, it's easier to understand kP values as output/error where output is volts and error is meters but for the actual sparkmax controller, this number is in native units. take a look at SwerveIOFalcon to see how to turn this into native sensor units (hint you need to use the sensors you created above)

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/ElevatorIOSim.kt
> +  override fun updateInputs(inputs: ElevatorIO.ElevatorInputs) {
should add a mechanism 2d object that is connected to the elevator. the height of the 2d object should be updated in `updateInputs()` where you feed the elevatorPosition

2023-01-21 03:22 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/ElevatorIOSim.kt
> +    elevatorSim.setInputVoltage(RoboRioSim.getVInVoltage() * percentOutput)
should switch to using volts? im anti percentOutput because although it's right, this line isn't very intuitive tbh

2023-01-30 21:57 UTC, plusparth requested changes
great work! I would read through comments on ground intake first, because some stuff I said there I didn't repeat here. The biggest change I think would be beneficial is getting rid of the distinction between actual and desired states, and just having a way to check if we are at the desired state currently. Then the hashmap thing for being able to tune the setpoints that correspond to each state would be helpful as well for easy tuning once the robot is built. Overall looks good though 👍

2023-01-31 12:54 UTC, sswadkar commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/ElevatorIOSim.kt
> +    val elevatorHome = m_mech2d.getRoot("Elevator Home", 55.0, 0.0)
i'm not sure how much overhead this produces. mechanism2d isn't the most efficient thing to be constantly running. i think what we should be doing is wrapping the mechanism2d stuff in logic class surrounded by an if statement that checks if we're in replay mode (using a `const`) and only then display mechanism2d stuff

2023-02-01 00:31 UTC, MatthewChoulas commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/Elevator.kt
> +  val currentState: ElevatorConstants.ActualElevatorStates
how is this different that what we're currently doing with desired state and currentState? isn't it the same but with diff variable names cause desiredState acts like ur idea for current state and current state has the functionality as  isAtCommandedPosition. So should we just change the var names?

2023-02-01 00:36 UTC, XaelZ commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/Elevator.kt
> +  var elevatorFeedforward =
There is no empty default constructor, so it won't let you just initialize, you have to have the parameters

2023-02-01 00:56 UTC, XaelZ commented on src/main/kotlin/com/team4099/robot2023/subsystems/elevator/Elevator.kt
> +    // val position = height/ElevatorConstants.ELEVATOR_ANGLE.sin
because it's easier to test in sim without converting height to position using trig

2023-03-08 06:27 UTC, closed without merging